### ISSUE TITLE
Task 2: Experience with GitHub & Git

### ISSUE THREAD

**Issue by nitishchauhan0022** [nitishchauhan0022/GSoC-pgRouting#1]
- [x] Fork the [GSoC-pgRouting](https://github.com/pgRouting/GSoC-pgRouting) repository
- [x] activate issues in your fork
- [x] open an issue in your fork and put this content on the issue
- [x] Clone your fork repository in your computer
- [x] Create remote named `upstream` pointing to https://github.com/pgRouting/GSoC-pgRouting
- [x] checkout to the `develop` branch of `upstream`
- [x] create new branch with name `<your-git-nick>-test`
- [x] Edit `doc/src/pgRouting-introduction.rst` and put your name on contributor
- [x] push the newly created branch with the change 
- [x] Create a pull request to https://github.com/pgRouting/GSoC-pgRouting
- [x] put link of the PR and of the issue on a comment on the issue you created on [GSoC-pgRouting (https://github.com/pgRouting/GSoC-pgRouting) repository

**Comment by nitishchauhan0022** [comment]
**### Task 1: Intent of application**

**Comment by nitishchauhan0022** [comment]
Task 1: Intent of application###

**Comment by nitishchauhan0022** [comment]
Task 1: Intent of application****

**Comment by nitishchauhan0022** [comment]
### **Task 1: Intent of application**

**Comment by nitishchauhan0022** [comment]
**### Task 1: Intent of application**

**Comment by nitishchauhan0022** [comment]
### Task 1: Intent of application

**Comment by nitishchauhan0022** [comment]
**Clone your fork repository in your computer**

`git clone https://github.com/nitishchauhan0022/GSoC-pgRouting.git`

> Cloning into 'GSoC-pgRouting'...
> remote: Enumerating objects: 116580, done.
> remote: Counting objects: 100% (16261/16261), done.
> remote: Compressing objects: 100% (4398/4398), done.
> remote: Total 116580 (delta 11493), reused 15867 (delta 11281), pack-reused 100319
> Receiving objects: 100% (116580/116580), 60.55 MiB | 763.00 KiB/s, done.
> Resolving deltas: 100% (83025/83025), done.

**Create remote named upstream pointing to https://github.com/pgRouting/GSoC-pgRouting**

`git remote -v`

> origin	https://github.com/nitishchauhan0022/GSoC-pgRouting.git (fetch)
> origin	https://github.com/nitishchauhan0022/GSoC-pgRouting.git (push)

```
git remote add upstream https://github.com/pgRouting/GSoC-pgRouting
git remote -v
```
> origin	https://github.com/nitishchauhan0022/GSoC-pgRouting.git (fetch)
> origin	https://github.com/nitishchauhan0022/GSoC-pgRouting.git (push)
> upstream	https://github.com/pgRouting/GSoC-pgRouting (fetch)
> upstream	https://github.com/pgRouting/GSoC-pgRouting (push)

**checkout to the develop branch of upstream**
`git checkout upstream/develop`

> Note: switching to 'upstream/develop'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by switching back to a branch.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -c with the switch command. Example:
> 
>   git switch -c <new-branch-name>
> 
> Or undo this operation with:
> 
>   git switch -
> 
> Turn off this advice by setting config variable advice.detachedHead to false
> 
> HEAD is now at 409c9e8f1 [docqueries][tsp] removing randomize parameter from calls (#2234)

 **create new branch with name <your-git-nick>-test**
`git checkout -b nitish-test`

> Switched to a new branch 'nitish-test'

**Edit doc/src/pgRouting-introduction.rst and put your name on contributor**
`nano doc/src/pgRouting-introduction.rst`

**push the newly created branch with the change**

`git status`

> On branch nitish-test
> Changes not staged for commit:
>   (use "git add <file>..." to update what will be committed)
>   (use "git restore <file>..." to discard changes in working directory)
> 	modified:   doc/src/pgRouting-introduction.rst

` git add doc/src/pgRouting-introduction.rst`

`git commit -m "task 2:adding name in contributor list"`

> [nitish-test 0b3653d59] task 2:adding name in contributor list
>  1 file changed, 1 insertion(+)

`git push origin nitish-test`

> Username for 'https://github.com': nitishchauhan0022
> Password for 'https://nitishchauhan0022@github.com': 
> Enumerating objects: 9, done.
> Counting objects: 100% (9/9), done.
> Delta compression using up to 16 threads
> Compressing objects: 100% (5/5), done.
> Writing objects: 100% (5/5), 452 bytes | 452.00 KiB/s, done.
> Total 5 (delta 4), reused 0 (delta 0)
> remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
> remote: 
> remote: Create a pull request for 'nitish-test' on GitHub by visiting:
> remote:      https://github.com/nitishchauhan0022/GSoC-pgRouting/pull/new/nitish-test
> remote: 
> To https://github.com/nitishchauhan0022/GSoC-pgRouting.git
>  * [new branch]          nitish-test -> nitish-test
